statsservice/models/stats.py
import uuid
from datetime import datetime

from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID

from statsservice.bootstrap import db


class Stats(db.Model):
    """Represent a single stats from a MONARC instance.
    The type can be one value from the folowing:
    "risk", "vulnerability", "threat", "cartography", "compliance".
    """

    uuid = db.Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        unique=True,
        nullable=False,
    )
    anr = db.Column(UUID(as_uuid=True), nullable=False)
    type = db.Column(db.String(), index=True, nullable=False)
    date = db.Column(db.Date(), index=True, nullable=False)
    data = db.Column(JSONB, default={}, nullable=False)
    created_at = db.Column(db.DateTime(), default=datetime.utcnow)

    # foreign keys
    client_id = db.Column(db.Integer(), db.ForeignKey("client.id"), default=None)

    def __str__(self):
        return """Client {}
ANR: {}
Type: {}
Date: {}
Data: {}
Created at: {}
""".format(
            self.client.name, self.anr, self.type, self.date, self.data, self.created_at
        )

    def _asdict(self):
        return {
            "uuid": str(self.uuid),
            "anr": str(self.anr),
            "type": self.type,
            "date": self.date.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "data": self.data,
        }

statsservice/views/map.py
#! /usr/bin/env python
import operator

from flask import Blueprint
from flask import jsonify
from flask import render_template

import statsservice.lib.processors
from statsservice.models import Client
from statsservice.models import Stats


# stats_bp: blueprint for public only routes which returns different kind of statistics
map_bp = Blueprint("map_bp", __name__, url_prefix="/map")


@map_bp.route("/", methods=["GET"])
def index():
    return render_template("map.html")


@map_bp.route("/clients.json", methods=["GET"])
def clients():
    clients = Client.query.filter(
        Client.latitude != None, Client.longitude != None  # noqa
    ).all()

    result = []

    for client in clients:
        query = Stats.query.filter(Stats.type == "threat", Stats.client_id == client.id)
        query = query.order_by(Stats.date.desc()).limit(40)
        if not query.count():
            continue
        threats = getattr(  # noqa
            statsservice.lib.processors, "threat_average_on_date"
        )(query.all())
        try:
            max_threat = max(
                ((threat["averages"]["count"], threat["object"]) for threat in threats),
                key=operator.itemgetter(0),
            )
        except ValueError:
            # ValueError: max() arg is an empty sequence
            max_threat = ("", "")

        query = Stats.query.filter(
            Stats.type == "vulnerability", Stats.client_id == client.id
        )
        query = query.order_by(Stats.date.desc()).limit(40)
        if not query.count():
            continue
        vulnerabilities = getattr(  # noqa
            statsservice.lib.processors, "vulnerability_average_on_date"
        )(query.all())
        try:
            max_vulnerability = max(
                (
                    (vulnerability["averages"]["count"], vulnerability["object"])
                    for vulnerability in vulnerabilities
                ),
                key=operator.itemgetter(0),
            )
        except ValueError:
            # ValueError: max() arg is an empty sequence
            max_vulnerability = ("", "")

        result.append(
            {
                "latitude": client.latitude,
                "longitude": client.longitude,
                "max_threat": max_threat,
                "max_vulnerability": max_vulnerability,
            }
        )

    return jsonify(result)

statsservice/views/root.py
#! /usr/bin/env python
# Stats service API for MONARC
# Copyright (C) 2020-2024 Cédric Bonhomme - https://www.cedricbonhomme.org
# Copyright (C) 2020-2024 NC3 Luxembourg
#
# For more information: https://github.com/monarc-project/stats-service
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import sys

from flask import Blueprint
from flask import jsonify
from flask import render_template
from flask import url_for

from statsservice import __version__
from statsservice.bootstrap import application
from statsservice.models import Client
from statsservice.models import Stats


# root_bp: blueprint of higher level routes
root_bp = Blueprint("root_bp", __name__, url_prefix="")


@root_bp.route("/", methods=["GET"])
def home():
    """For the moment simply redirects to the documentation of the API."""
    return render_template("index.html")


@root_bp.route("evolution", methods=["GET"])
def evolution():
    """The only view of this blueprint which is supposed to return a HTML file.
    Routes defined in the following can be used in this HTML file.
    """
    return render_template("evolution.html")


@root_bp.route("help", methods=["GET"])
def help():
    """About page."""
    return render_template("help.html")


@root_bp.route("about", methods=["GET"])
def about():
    """About page."""
    return render_template("about.html")


@root_bp.route("/about/more", methods=["GET"])
def about_more():
    """Returns some details about the current Stats Service instance."""
    version = __version__.split("-")
    if len(version) == 1:
        stats_service_version = version[0]
        version_url = (
            "https://github.com/monarc-project/stats-service/releases/tag/{}".format(
                version[0]
            )
        )
    else:
        stats_service_version = f"{version[0]} - {version[2][1:]}"
        version_url = (
            "https://github.com/monarc-project/stats-service/commits/{}".format(
                version[2][1:]
            )
        )
    return render_template(
        "about_more.html",
        stats_service_version=stats_service_version,
        version_url=version_url,
        python_version="{}.{}.{}".format(*sys.version_info[:3]),
        nb_contributors=Client.query.count(),
        nb_stats=Stats.query.count(),
    )


@root_bp.route("about.json", methods=["GET"])
def about_json():
    """Provide information about the instance."""
    version = __version__.split("-")
    if len(version) == 1:
        stats_version = version[0]
        version_url = (
            "https://github.com/monarc-project/stats-service/releases/tag/{}".format(
                version[0]
            )
        )
    else:
        stats_version = f"{version[0]} - {version[2][1:]}"
        version_url = (
            "https://github.com/monarc-project/stats-service/commits/{}".format(
                version[2][1:]
            )
        )

    return jsonify(
        version=stats_version,
        version_url=version_url,
        api_v1_root=url_for("api.doc"),
        contact=application.config["ADMIN_EMAIL"],
    )


@root_bp.route("human.txt", methods=["GET"])
def human():
    """Human dot txt page."""
    return render_template("human.txt"), 200, {"Content-Type": "text/plain"}


@root_bp.route("robots.txt", methods=["GET"])
def robots():
    """Robots dot txt page."""
    return render_template("robots.txt"), 200, {"Content-Type": "text/plain"}


@root_bp.route("/.well-known/security.txt", methods=["GET"])
def security():
    """security dot txt page (RFC 9116)."""
    return render_template("security.txt"), 200, {"Content-Type": "text/plain"}

statsservice/views/stats.py
#! /usr/bin/env python
from datetime import datetime
from datetime import timedelta

from flask import abort
from flask import Blueprint
from flask import jsonify
from flask import request

import statsservice.lib.processors
from statsservice.models import Stats


# stats_bp: blueprint for public only routes which returns different kind of statistics
stats_bp = Blueprint("stats_bp", __name__, url_prefix="/stats")

# Do not use query filters on Client or on ANR here. It would be in
# contradiction with the finality of this blueprint.


@stats_bp.route("/threats.json", methods=["GET"])
def threats():
    """Returns threats with custom processings."""
    now = datetime.today()
    nb_days = request.args.get("days", default=365, type=int)
    last_stats = request.args.get("last_stats", default=0, type=int)
    local_stats_only = request.args.get("local_stats_only", default=0, type=int)
    processor = request.args.get(
        "processor", default="threat_average_on_date", type=str
    )

    query = Stats.query.filter(Stats.type == "threat")
    if local_stats_only:
        query = query.filter(Stats.client.has(local=True))
    if last_stats:
        query = query.order_by(Stats.date.desc()).limit(40)
    else:
        query = query.filter(Stats.date >= now - timedelta(days=nb_days))

    try:
        result = getattr(statsservice.lib.processors, processor)(query.all())
    except AttributeError:
        abort(
            500,
            description=f"There is no such processor: '{processor}'.",
        )

    return jsonify(result)


@stats_bp.route("/risks.json", methods=["GET"])
def risks():
    """Returns risks with custom processings."""
    now = datetime.today()
    nb_days = request.args.get("days", default=365, type=int)
    last_stats = request.args.get("last_stats", default=0, type=int)
    local_stats_only = request.args.get("local_stats_only", default=0, type=int)
    processor = request.args.get(
        "processor", default="threat_average_on_date", type=str
    )

    query = Stats.query.filter(Stats.type == "risk")
    if local_stats_only:
        query = query.filter(Stats.client.has(local=True))
    if last_stats:
        query = query.order_by(Stats.date >= now - timedelta(days=40))
    else:
        query = query.filter(Stats.date >= now - timedelta(days=nb_days))

    try:
        result = getattr(statsservice.lib.processors, processor)(query.all())
    except AttributeError:
        abort(
            500,
            description=f"There is no such processor: '{processor}'.",
        )

    return jsonify(result)


@stats_bp.route("/vulnerabilities.json", methods=["GET"])
def vulnerabilities():
    """Returns vulnerabilities with custom processings."""
    now = datetime.today()
    nb_days = request.args.get("days", default=365, type=int)
    last_stats = request.args.get("last_stats", default=0, type=int)
    local_stats_only = request.args.get("local_stats_only", default=0, type=int)
    processor = request.args.get(
        "processor", default="vulnerability_average_on_date", type=str
    )

    query = Stats.query.filter(Stats.type == "vulnerability")
    if local_stats_only:
        query = query.filter(Stats.client.has(local=True))
    if last_stats:
        query = query.order_by(Stats.date >= now - timedelta(days=40))
    else:
        query = query.filter(Stats.date >= now - timedelta(days=nb_days))

    try:
        result = getattr(statsservice.lib.processors, processor)(query.all())
    except AttributeError:
        abort(
            500,
            description=f"There is no such processor: '{processor}'.",
        )

    return jsonify(result)

statsservice/templates/about.html
{% extends "layout.html" %}
{% set active_page = "about" %}
{% block content %}
<div class="container" role="main">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1>MONARC Stats Service</h1>
        <p>{{ _('This software is released under AGPLv3 license and is maintained by
        <a href="https://www.nc3.lu" target="_blank" rel="noopener noreferrer">NC3 Luxembourg</a>.') }}
        <br />
        {{ _('You are welcome to copy, modify or
        redistribute the <a href="https://github.com/monarc-project/stats-service" target="_blank" rel="noopener noreferrer">source code</a>
        according to the <a href="https://www.gnu.org/licenses/agpl-3.0.html" target="_blank" rel="noopener noreferrer">Affero GPL</a> license.</p>
        <p>Found a bug? Report it <a href="https://github.com/monarc-project/stats-service/issues" target="_blank" rel="noopener noreferrer">here</a>.') }}
        <p class="text-justify">
          <a href="{{ url_for('root_bp.help') }}">{{ _('Help and documentation.') }}</a>
          <br /><br />
          <a href="{{ url_for('root_bp.about_more') }}">{{ _('More information') }}</a> {{ _('about this instance.') }}
        </p>
        <img class="mx-auto d-block" src="{{ url_for('static', filename='img/apple-touch-icon.png') }}" width="240" alt="Logo of MONARC Stats Service" title="Logo of MONARC Stats Service">
    </div>
  </div>
</div><!-- /.container -->
{% endblock %}

statsservice/templates/about_more.html
{% extends "layout.html" %}
{% block content %}
<div class="container" role="main">
    <div class="row justify-content-center">
        <div class="col-md-6">
          <h1>{{ _('Information about this instance') }}</h1>
          <ul class="list-group">
            <li class="list-group-item">{{ _('Stats service version:') }} <a href="{{version_url}}" target="_blank" rel="noopener noreferrer">{{stats_service_version}}</a></li>
            <li class="list-group-item">{{ _('Python version:') }} {{python_version}}</li>
            <li class="list-group-item">{{ _('Number of contributors:') }} {{nb_contributors}}</li>
            <li class="list-group-item">{{ _('Number of stats:') }} {{nb_stats}}</li>
            <li class="list-group-item">{{ _('Contact:') }} <a href="mailto:{{ config['ADMIN_EMAIL'] }}">{{ config['ADMIN_EMAIL'] }}</a></li>
          </ul>
        </div>
    </div>
</div>
{% endblock %}

statsservice/templates/evolution.html
{% extends "layout.html" %}
{% set active_page = "evolution" %}
{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='js/evolutionCharts.js') }}"></script>
{% endblock %}
{% block content %}
<div class="container-fluid p-2" role="main">
  <h2>{{ _('Evolution') }}</h2>
  <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-threatsEvolution-tab" data-bs-toggle="tab" href="#nav-threatsEvolution" role="tab" aria-controls="nav-threatsEvolution" aria-selected="true">{{ _('Threats evolution')}}</a>
        <a class="nav-item nav-link" id="nav-vulnerabilitiesEvolution-tab" data-bs-toggle="tab" href="#nav-vulnerabilitiesEvolution" role="tab" aria-controls="nav-vulnerabilitiesEvolution" aria-selected="false">{{ _('Vulnerabilities evolution') }}</a>
      </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active p-4" id="nav-threatsEvolution" role="tabpanel" aria-labelledby="nav-threatsEvolution-tab">
          <div class="row d-flex justify-content-center">
              <div class="col-md-auto">
                  <label for="displayThreatsEvolutionBy">{{ _('Display by')}}</label>
                  <select id="displayThreatsEvolutionBy">
                    <option value="averageRate" selected>{{ _('Probability')}}</option>
                    <option value="count">{{ _('Occurrence')}}</option>
                    <option value="maxRisk">{{ _('Max. associated risk level')}}</option>
                  </select>
              </div>
              <div class="col-md-auto">
                  <label for="orderThreatsEvolutionBy">{{ _('Order by')}}</label>
                  <select id="orderThreatsEvolutionBy">
                    <option value="highest" selected>{{ '20 ' +_('Highest')}}</option>
                    <option value="lowest">{{ '20 ' + _('Lowest')}}</option>
                  </select>
              </div>
              <div class="dropdown col-1" data-toggle="tooltip" title="{{ _ ('Export')}}">
                  <i class="bi-save-fill text-primary" type="button" id="threatsEvolutionMenuExport" data-bs-toggle="dropdown" aria-expanded="false">
                  </i>
                  <ul class="dropdown-menu" aria-labelledby="threatsEvolutionMenuExport" style="min-width:1rem">
                    <li><a class="dropdown-item" type="button" id="exportThreatsEvolutionPNG">.png</a></li>
                    <li><a class="dropdown-item" id="exportThreatsEvolutionCSV">.csv</a></li>
                  </ul>
              </div>
          </div>
          <div class="d-flex justify-content-center py-5" id="spinner-threatsEvolution">
              <div class="spinner-border " style="width: 8rem; height: 8rem;"></div>
          </div>
          <div class="mx-auto py-3 chart-container evolutionChart">
            <div class="legend-tooltip" role="tooltip" id="legendTooltip-threatsEvolution"></div>
            <canvas id="canvas-threatsEvolution"></canvas>
            <div class="d-flex justify-content-end pe-5 pt-2">
              <button class="btn btn-secondary" type="button" style="display: none;" id="inversethreatsEvolutionSelection">{{ _('Inverse selection')}}</button>
            </div>
          </div>
      </div>
      <div class="tab-pane fade p-4" id="nav-vulnerabilitiesEvolution" role="tabpanel" aria-labelledby="nav-vulnerabilitiesEvolution-tab">
          <div class="row d-flex justify-content-center">
              <div class="col-md-auto">
                  <label for="displayVulnerabilitiesEvolutionBy">{{ _('Display by')}}</label>
                  <select id="displayVulnerabilitiesEvolutionBy">
                    <option value="averageRate" selected>{{ _('Probability')}}</option>
                    <option value="count">{{ _('Occurrence')}}</option>
                    <option value="maxRisk">{{ _('Max. associated risk level')}}</option>
                  </select>
              </div>
              <div class="col-md-auto">
                  <label for="orderVulnerabilitiesEvolutionBy">{{ _('Order by')}}</label>
                  <select id="orderVulnerabilitiesEvolutionBy">
                    <option value="highest" selected>{{ '20 ' + _('Highest')}}</option>
                    <option value="lowest">{{ '20 ' + _('Lowest')}}</option>
                  </select>
              </div>
              <div class="dropdown col-1" data-toggle="tooltip" title="{{ _ ('Export')}}">
                <i class="bi-save-fill text-primary" type="button" id="vulnerabilitiesEvolutionMenuExport" data-bs-toggle="dropdown" aria-expanded="false">
                </i>
                <ul class="dropdown-menu" aria-labelledby="vulnerabilitiesEvolutionMenuExport" style="min-width:1rem">
                  <li><a class="dropdown-item" type="button" id="exportVulnerabilitiesEvolutionPNG">.png</a></li>
                  <li><a class="dropdown-item" id="exportVulnerabilitiesEvolutionCSV">.csv</a></li>
                </ul>
              </div>
          </div>
          <div class="d-flex justify-content-center py-5" id="spinner-vulnerabilitiesEvolution">
            <div class="spinner-border" style="width: 8rem; height: 8rem;"></div>
          </div>
          <div class="mx-auto py-3 chart-container evolutionChart">
            <div class="legend-tooltip" id="legendTooltip-vulnerabilitiesEvolution"></div>
            <canvas id="canvas-vulnerabilitiesEvolution"></canvas>
            <div class="d-flex justify-content-end pe-5 pt-2">
              <button class="btn btn-secondary" type="button" style="display: none;" id="inversevulnerabilitiesEvolutionSelection">{{ _('Inverse selection')}}</button>
            </div>
          </div>
      </div>
  </div>
</div>
<script>
    SITE_ROOT = "{{ config['INSTANCE_URL'] }}";
    drawEvolutionChart();
</script>
{% endblock %}

statsservice/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="{{ _('MONARC Dashboard') }}" />
  <meta name="author" content="NC3.lu - Cyberworld Awareness and Security Enhancement Services" />
   <meta name="keywords" content="MONARC, stats, threats, vulnerabilities, infosec">
  <link rel="author" type="text/plain"  href="{{ url_for('root_bp.human')  }}" />
  <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.ico') }}" />
  <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='img/apple-touch-icon.png') }}">
  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/apple-touch-icon.png') }}" />
  <title>Global dashboard</title>
  {% block head_css %}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='npm_components/bootstrap/dist/css/bootstrap.min.css') }}" media="screen" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/custom.css') }}" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='npm_components/bootstrap-icons/font/bootstrap-icons.css') }}" />
  {% endblock %}
  <script type="text/javascript" src="{{ url_for('static', filename='npm_components/@popperjs/core/dist/umd/popper.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='npm_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/chart.js/dist/chart.umd.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/moment/min/moment.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/chartjs-adapter-moment/dist/chartjs-adapter-moment.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/lodash.clonedeep/index.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/d3-color/dist/d3-color.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/d3-interpolate/dist/d3-interpolate.min.js') }}"></script>
  <script src="{{ url_for('static', filename='npm_components/d3-scale-chromatic/dist/d3-scale-chromatic.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/utils.js') }}"></script>
  <script src="{{ url_for('static', filename='js/threatsCharts.js') }}"></script>
  <script src="{{ url_for('static', filename='js/vulnerabilitiesCharts.js') }}"></script>
  <script src="{{ url_for('static', filename='js/risksCharts.js') }}"></script>
  {% endblock %}
</head>
{% block page_body %}
<body>
  {% block menu %}
  {% set active_page = active_page|default('index') -%}
  <nav class="navbar navbar-expand-lg navbar-dark bg-custom-blue">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('root_bp.home') }}">
        <img src="{{ url_for('static', filename='img/apple-touch-icon.png') }}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
        MONARC Dashboard
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% block menu_links %}
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link {% if active_page == "index" %}active{%endif%}" href="{{ url_for('root_bp.home') }}">{{_('Current stats')}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if active_page == "evolution" %}active{%endif%}" href="{{ url_for('root_bp.evolution') }}">{{_('Evolution')}}</a>
          </li>
          {% if "map_bp" in config.ACTIVE_BLUEPRINTS %}
          <li class="nav-item">
            <a class="nav-link {% if active_page == "map" %}active{%endif%}" href="{{ url_for('map_bp.index') }}">{{_('Map')}}</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link {% if active_page == "about" %}active{%endif%}" href="{{ url_for('root_bp.about') }}">{{_('About')}}</a>
          </li>
        </ul>
      </div>
      {% endblock %}
    </div>
  </nav>
  {% endblock %}
  {% block content %}{% endblock %}
  <br />
  <footer class="footer">
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <a href="{{ url_for('root_bp.about') }}" title="About">{{ _('About') }}</a>
          &nbsp;&nbsp;
          <a href="{{ url_for('root_bp.help') }}" title="Help">{{ _('Help') }}</a>
          &nbsp;&nbsp;
          <a href="{{ url_for('api.doc') }}">{{ _('OpenAPI Specification') }}</a>
        </div>
      </div>
    </div>
  </footer>
</body>
{% endblock %}
</html>

statsservice/templates/map.html
{% extends "layout.html" %}
{% set active_page = "map" %}
{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='npm_components/leaflet/dist/leaflet.css') }}" />
<script src="{{ url_for('static', filename='npm_components/leaflet/dist/leaflet.js') }}"></script>
<script src="{{ url_for('static', filename='js/map.js') }}"></script>
{% endblock %}
{% block content %}
<div class="container-fluid" role="main">
  <h1>{{ _('Cybersecurity Weather Map') }}</h1>
  <div  class="map map-home mapChart col-md-10 mx-auto" id="cyberweathermap"></div>
  <div class="col-md-12">
      <p>{{ _('Based on the statistics collected, this map presents the highest current threats and vulnerabilities, by region.') }}</p>
      <p>{{ _('You can also') }} <a href="{{ url_for('root_bp.help') }}#share">{{ _('share statistics') }}</a>.</p>
  </div>
</div><!-- /.container -->
<script>
  drawMap();
</script>
{% endblock %}

statsservice/templates/stats.html
{% extends "layout.html" %}
{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='js/utils.js') }}"></script>
<script src="{{ url_for('static', filename='js/evolutionCharts.js') }}"></script>
{% endblock %}
{% block content %}
<div class="container-fluid" role="main">
  <div class="row justify-content-center">
    <div class="col">
      <h1>{{ _('Evolution') }}</h1>
    </div>
  </div>
    <div class="row justify-content-center">
      <div class="col-md-12">
        <h2 id="trends-threats">{{ _('Threats') }}</h2>
        <div class="d-flex justify-content-center">
          <div id="spinner-threats" class="spinner-border" style="width: 8rem; height: 8rem;"></div>
        </div>
        <div class="d-flex justify-content-center">
          <div class="chart-container" style="position: relative; width:80vw">
            <canvas id="canvas-threats"></canvas>
          </div>
        </div>
        <!-- <div id="my-legend-con" class="legend-con"></div> -->
        <br />
        <p>The values are based on the <i>averageRate</i> of the <a href="https://objects.monarc.lu/schema/15" rel="noreferrer" target="_blank">threats</a>.<sup><a href="#footnote-1">[1]</a></sup>.</p>
      </div>
    </div>
    <br /><hr /><br />
    <div class="row justify-content-center">
      <div class="col">
        <h2 id="trends-vulnerabilities">{{ _('Vulnerabilities') }}</h2>
        <div class="d-flex justify-content-center">
          <div id="spinner-vulnerabilities" class="spinner-border" style="width: 8rem; height: 8rem;"></div>
        </div>
        <div class="d-flex justify-content-center">
          <div class="chart-container" style="position: relative; width:80vw">
            <canvas id="canvas-vulnerabilities"></canvas>
          </div>
        </div>
        <br />
        <p>The values are based on the <i>averageRate</i> of the <a href="https://objects.monarc.lu/schema/14" rel="noreferrer" target="_blank">vulnerabilities</a>.<sup><a href="#footnote-1">[1]</a></sup>.</p>
      </div>
    </div>

    <hr />

    <div class="row">
      <div class="col-md-12">
        <ol class="footnotes">
          <li id="footnote-1">Averages per date of the different averageRate for threats and vulnerabilities.</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container -->
  <script>
      drawEvolutionChart();
  </script>
  {% endblock %}